// Code generated by mockery v2.42.0. DO NOT EDIT.

package usecase

import (
	context "context"

	entity "github.com/gandarez/redhat-meetup-2024-04-02/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockConsoleRepositoryFinder is an autogenerated mock type for the ConsoleRepositoryFinder type
type MockConsoleRepositoryFinder struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockConsoleRepositoryFinder) FindByID(ctx context.Context, id string) (*entity.Console, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Console
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Console, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Console); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Console)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockConsoleRepositoryFinder creates a new instance of MockConsoleRepositoryFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsoleRepositoryFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsoleRepositoryFinder {
	mock := &MockConsoleRepositoryFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
