// Code generated by mockery v2.42.0. DO NOT EDIT.

package usecase

import (
	context "context"

	entity "github.com/gandarez/redhat-meetup-2024-04-02/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockConsoleRepositoryCreator is an autogenerated mock type for the ConsoleRepositoryCreator type
type MockConsoleRepositoryCreator struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, console
func (_m *MockConsoleRepositoryCreator) Save(ctx context.Context, console *entity.Console) error {
	ret := _m.Called(ctx, console)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Console) error); ok {
		r0 = rf(ctx, console)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockConsoleRepositoryCreator creates a new instance of MockConsoleRepositoryCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsoleRepositoryCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsoleRepositoryCreator {
	mock := &MockConsoleRepositoryCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
